FROM arm32v7/python:3.6-slim

MAINTAINER Roman Zhukov

WORKDIR /app

ENV MQTT_HOST="localhost"
ENV MQTT_PORT=1823
ENV MQTT_LOGIN=""
ENV MQTT_PASS=""
ENV MQTT_TOPIC_PREFIX="rtl_433"

#
# First install software packages needed to compile rtl_433 and to publish MQTT events
#
RUN apt-get update && \
    apt-get install -y git libtool libusb-1.0.0-dev librtlsdr-dev rtl-sdr cmake automake && \
    mkdir /tmp/src && \
    cd /tmp/src && \
    git clone git://git.osmocom.org/rtl-sdr.git && \
    mkdir /tmp/src/rtl-sdr/build && \
    cd /tmp/src/rtl-sdr/build && \
    cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr/local && \
    make && \
    make install && \
    chmod +s /usr/local/bin/rtl_* && \
    cd /tmp/src/ && \
    git clone https://github.com/merbanan/rtl_433.git && \
    cd rtl_433/ && \
    mkdir build && \
    cd build && \
    cmake ../ && \
    make && \
    make install && \
    rm -r /tmp/src && \
    apt-get install -y mosquitto-clients

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY run.py .

CMD python3 -u run.py

